from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import uvicorn
import requests
import os
import json
from pydantic import BaseModel
from sqlalchemy.orm import Session
from database.db import engine, get_db, Base
from database.models import Product
from rag_engine import retrieve_top_k
from dotenv import load_dotenv

BASE_DIR = os.path.dirname(__file__)
load_dotenv(os.path.join(BASE_DIR, ".env"))

Base.metadata.create_all(bind=engine)

app = FastAPI(title="Skincare Guru API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mistral removed as fallback


class ChatRequest(BaseModel):
    step: int
    data: dict


RECOMMENDATION_SYSTEM_PROMPT = """
You are SkinCare Guru — a friendly, expert skincare consultant who speaks in a warm and approachable tone.

Your job is to select the MOST RELEVANT products from a provided dataset and present them in a way that feels like personalized advice from a trusted professional.

You DO NOT behave like a generic chatbot or a cold recommendation engine.
You behave like a knowledgeable skincare friend who genuinely understands the user's needs.

--------------------------------------------------
INPUT
--------------------------------------------------
You will receive:
1. A normalized user profile (skin type, concerns, age, experience, focus area, routine timing)
2. A product dataset array
3. A pre-scored shortlist generated by the application

--------------------------------------------------
HARD CONSTRAINTS
--------------------------------------------------
You MUST strictly filter products:
1. category MUST match the requested area exactly after normalization
2. concern MUST be present in product.concerns
3. skin_type must match OR be compatible ("All" is universal)

If no results:
relax ONLY the concern constraint, never the category constraint

Never invent products. Only use products from the provided dataset.

--------------------------------------------------
SCORING RULES
--------------------------------------------------
Use the application's scoring signals as primary truth.
The provided product scores already reflect:
+5 exact concern match
+3 skin type exact match
+2 skin type compatible / all
+2 effect or ingredient alignment with concern
+1 beginner friendly when relevant
+1 simple / popular / low-complexity profile
-2 too complex for beginner
-3 harsh for sensitive skin

If you must break ties, prefer:
1. higher app_score
2. better routine step coverage
3. simpler beginner-safe product

--------------------------------------------------
ROUTINE RULES
--------------------------------------------------
If flow = "Build My Routine":
- Return a structured morning and evening routine based on "routine_timing" from the user profile.
- If routine_timing is "Morning", return ONLY the morning routine. Leave the evening routine empty.
- If routine_timing is "Evening", return ONLY the evening routine. Leave the morning routine empty.
- If routine_timing is "Complete", return BOTH morning and evening routines.
- Beginner: maximum 4 total recommended steps per routine block
- Advanced/Expert: layered actives allowed only when the shortlist supports it

Sensitive skin:
- Avoid strong retinoids, peeling acids, harsh exfoliants unless no safer shortlist exists

Acne:
- Prefer salicylic acid, niacinamide, oil-control, non-comedogenic support

Dryness:
- Prefer hyaluronic acid, ceramides, glycerin, barrier repair

Aging:
- Prefer retinol, peptides, vitamin C, barrier-supportive companions

--------------------------------------------------
OUTPUT RULES
--------------------------------------------------
Return STRICT JSON ONLY.
Do not output markdown.
Do not output commentary outside JSON.
Do not hallucinate fields.

Return exactly this schema:
{
  "title": "string",
  "analysis": "string",
  "solution": "string",
  "recommendations": [
    {
      "product_name": "string",
      "score": 0,
      "description": "string",
      "reason": "string",
      "matched_attributes": ["string"]
    }
  ],
  "routine": {
    "morning": ["string"],
    "evening": ["string"]
  },
  "notes": "string"
}

Rules for the JSON:
- **title**: Write a warm, specific title. Instead of generic "Face Routine", write something like "Your Morning Glow Routine for Oily Skin" or "Hydration Rescue Kit for Dry, Sensitive Skin". Reference the user's actual skin type, concern, or goal.
- **analysis**: Write 2-4 sentences explaining the user's skin situation in a warm, educational tone. Describe WHAT the concern/problem is, WHY it happens (root causes like excess sebum, dehydrated barrier, UV damage, hormonal changes, etc.), and how the user's specific skin type, age, and lifestyle make it relevant. Example for oily+acne: "Acne on oily skin happens when excess sebum clogs your pores, creating a breeding ground for bacteria. In your 20s, hormonal fluctuations can make this worse, especially in the T-zone. Your oily skin type means you need oil-control without harsh stripping that triggers even more oil production." Do NOT be generic — reference the user's actual inputs.
- **solution**: Write 2-3 sentences describing the recommended approach/strategy BEFORE listing products. Explain the skincare philosophy behind your picks. Example: "The key is a gentle-but-effective routine: a salicylic acid cleanser to unclog pores, a lightweight moisturizer to keep your barrier happy, and a niacinamide serum to regulate oil. We're keeping it simple since you're a beginner — no overwhelming multi-step routine."
- **description**: For each product, write 1-2 sentences describing what the product IS and what it DOES (its purpose, key ingredients, how it works). Example: "A lightweight gel cleanser infused with 2% salicylic acid that penetrates deep into pores to dissolve oil and dead skin buildup without over-drying."
- **reason**: For each product, write a short sentence explaining WHY this product was picked for THIS specific user. Example: "Perfect for your oily skin — controls shine while keeping your moisture barrier intact." Speak like a consultant, not a database.
- **product_name** must exactly match a provided product name
- **score** must be numeric
- **matched_attributes** must mention only real matching factors from the provided data
- If routine is not applicable, return empty arrays
- recommendations must be sorted highest score first
- Return exactly the number of products specified in `selection_rule.target_recommendation_count` (found in the input payload).
- **notes**: Write a friendly, actionable tip. Example: "Start with the cleanser and moisturizer for the first week, then gradually add the serum. Always patch-test new products on a small area first."
""".strip()


# ---------------- FLOW HANDLERS ---------------- #

def handle_routine_flow(step, user_data, db):
    if step == 1:
        return {
            "message": "When would you like this routine?",
            "options": ["Morning", "Evening", "Complete"],
            "next_step": 2,
            "data_key": "routine"
        }

    elif step == 2:
        return {
            "message": "Which area should we focus on?",
            "options": ["Face Care", "Body Care","Hair Care"],
            "next_step": 3,
            "data_key": "focus"
        }

    elif step == 3:
        return {
            "message": "Your Skin type?",
            "options": ["Normal", "Sensitive", "Oily", "Dry", "Combination"],
            "next_step": 4,
            "data_key": "skin"
        }

    elif step == 4:
        return {
            "type": "form",
            "message": "Tell us a bit more about you.",
            "groups": [
                {
                    "title": "What's your age range?",
                    "options": ["Under 18", "18-24", "25-34", "35-44", "45-54", "55+"],
                    "data_key": "age"
                },
                {
                    "title": "What's your skincare experience level?",
                    "options": ["Beginner", "Intermediate", "Advanced", "Expert"],
                    "data_key": "experience"
                }
            ],
            "next_step": 5
        }

    elif step == 5:
        return generate_routine(user_data, db)


def handle_concern_flow(step, user_data, db):
    if step == 1:
        return {
            "type": "vertical_cards",
            "message": "Which area needs some extra care?",
            "options": [
                {"title": "Face", "desc": "Complexion & facial skin"},
                {"title": "Body", "desc": "Full body skin wellness"},
                {"title": "Hair & Scalp", "desc": "Hair health & styling"},
                {"title": "Lips", "desc": "Lip-care & treatment"}
            ],
            "next_step": 2,
            "data_key": "area"
        }

    elif step == 2:
        area = user_data.get("area", "Body")
        return {
            "type": "form",
            "message": "Tell us more about your concern.",
            "groups": [
                {
                    "title": f"1. What area of your {area} is most affected?",
                    "type": "textarea",
                    "placeholder": f"e.g. {'cheeks, forehead' if area == 'Face' else 'Arms, Legs, Scalp'}...",
                    "data_key": "specific_area"
                },
                {
                    "title": "2. Can you describe how the skin feels or looks?",
                    "type": "textarea",
                    "placeholder": "e.g. dry, flaky, red, oily...",
                    "data_key": "symptoms"
                },
                {
                    "title": "3. Is this a recurring issue or something new?",
                    "type": "textarea",
                    "placeholder": "Describe if it's happened before...",
                    "data_key": "issue_history"
                },
                {
                    "title": f"4. What {area.lower()} products do you currently use?",
                    "type": "textarea",
                    "placeholder": "List your current products...",
                    "data_key": "current_products"
                },
                {
                    "title": "5. Are there any activities that seem to trigger or worsen it?",
                    "type": "textarea",
                    "placeholder": "e.g. exercise, certain foods, weather...",
                    "data_key": "triggers"
                }
            ],
            "next_step": 3
        }

    elif step == 3:
        return {
            "type": "form",
            "message": "Tell us a bit more about you.",
            "groups": [
                {
                    "title": "What's your age range?",
                    "options": ["Under 18", "18-24", "25-34", "35-44", "45-54", "55+"],
                    "data_key": "age"
                },
                {
                    "title": "What's your skincare experience level?",
                    "options": ["Beginner", "Intermediate", "Advanced", "Expert"],
                    "data_key": "experience"
                }
            ],
            "next_step": 4
        }

    elif step == 4:
        return generate_routine(user_data, db)


def handle_kit_flow(step, user_data, db):
    if step == 1:
        return {
            "type": "vertical_cards",
            "message": "Which kit should we build today?",
            "options": [
                {"title": "Daily Essentials", "desc": "Your everyday core must-haves"},
                {"title": "Travel Set", "desc": "TSA-friendly minis for your journey"},
                {"title": "Grooming Kit", "desc": "Complete grooming & hygiene set"},
                {"title": "Bridal Glow", "desc": "Ultimate pre-wedding radiance"}
            ],
            "next_step": 2,
            "data_key": "kit_type"
        }

    elif step == 2:
        return {
            "message": "Analysis: What's your skin type?",
            "options": ["Normal", "Dry", "Oily", "Combination", "Sensitive"],
            "next_step": 3,
            "data_key": "skin_type"
        }

    elif step == 3:
        return {
            "type": "kit_config",
            "message": "Configure your custom kit.",
            "concerns": {
                "title": "Select your main concerns",
                "options": ["Dryness", "Oiliness", "Acne", "Anti-aging", "Brightening", "Hydration", "Sensitivity", "Dullness"],
                "data_key": "concerns"
            },
            "quantity": {
                "title": "Number of products",
                "min": 3,
                "max": 6,
                "data_key": "product_count"
            },
            "next_step": 4
        }

    elif step == 4:
        return {
            "type": "form",
            "message": "One last thing...",
            "groups": [
                {
                    "title": "What's your age range?",
                    "options": ["Under 18", "18-24", "25-34", "35-44", "45-54", "55+"],
                    "data_key": "age"
                },
                {
                    "title": "What's your skincare experience level?",
                    "options": ["Beginner", "Intermediate", "Advanced", "Expert"],
                    "data_key": "experience"
                }
            ],
            "next_step": 5
        }

    elif step == 5:
        return generate_routine(user_data, db)


# ---------------- AI + RAG ---------------- #

def ask_llm(prompt, system_prompt=None):
    load_dotenv(os.path.join(BASE_DIR, ".env"), override=True)
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    
    if not OPENAI_API_KEY:
        return "⚠️ API Key missing. Please check your .env file."

    openai_url = "https://api.openai.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENAI_API_KEY}",
        "Content-Type": "application/json"
    }
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": prompt})
    payload = {
        "model": "gpt-4o-mini",
        "temperature": 0,
        "response_format": {"type": "json_object"} if system_prompt else None,
        "messages": messages
    }
    if payload["response_format"] is None:
        payload.pop("response_format")
    try:
        res = requests.post(openai_url, headers=headers, json=payload)
        res.raise_for_status()
        return res.json()["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"OpenAI Error: {e}")
        return "⚠️ The AI service is currently unavailable. Please check your API key and credits."

def ask_llm_safe(prompt, system_prompt=None):
    result = ask_llm(prompt, system_prompt=system_prompt)
    if not result or not result.strip():
        return None

    lowered = result.lower()
    if "api key missing" in lowered or "ai service is currently unavailable" in lowered:
        return None

    return result


def normalize_flow(intent):
    mapping = {
        "Build my Routine": "Build My Routine",
        "Help Me Fix a Concern": "Help Me Fix a Concern",
        "Create My Custom Kit": "Create My Custom Kit",
    }
    return mapping.get(intent, intent or "Build My Routine")


def normalize_category(user_data):
    raw_value = (user_data.get("focus") or user_data.get("area") or "Face").strip().lower()
    mapping = {
        "face": "Face",
        "face care": "Face",
        "body": "Body",
        "body care": "Body",
        "hair": "Hair",
        "hair care": "Hair",
        "hair & scalp": "Hair",
        "scalp": "Hair",
        "lips": "Lips",
        "lip": "Lips",
    }
    return mapping.get(raw_value, raw_value.title() if raw_value else "Face")


def normalize_skin_type(user_data):
    return (user_data.get("skin") or user_data.get("skin_type") or "Normal").strip().title()


def normalize_age_group(user_data):
    raw_age = (user_data.get("age") or "").strip()
    mapping = {
        "Under 18": "18-24",
        "45-54": "45+",
        "55+": "45+",
    }
    return mapping.get(raw_age, raw_age or "")


def normalize_experience(user_data):
    raw = (user_data.get("experience") or "Beginner").strip().title()
    if raw == "Expert":
        return "Advanced"
    return raw


def normalize_concern_tokens(user_data):
    raw_values = []
    concerns = user_data.get("concerns")
    if isinstance(concerns, list):
        raw_values.extend(concerns)
    elif concerns:
        raw_values.append(concerns)

    for key in ["kit_type", "symptoms", "specific_area"]:
        value = user_data.get(key)
        if value:
            raw_values.append(value)

    normalized = []
    concern_aliases = {
        "anti-aging": "Aging",
        "ageing": "Aging",
        "aging": "Aging",
        "brightening": "Dullness",
        "hydration": "Dryness",
        "oiliness": "Oily",
        "pimples": "Acne",
        "breakouts": "Acne",
        "dark spots": "Pigmentation",
    }

    for value in raw_values:
        for token in str(value).replace("/", ",").split(","):
            clean = token.strip().lower()
            if not clean:
                continue
            normalized.append(concern_aliases.get(clean, clean.title()))

    return list(dict.fromkeys(normalized))


def split_csv_text(value):
    if not value:
        return []
    return [part.strip() for part in str(value).replace("/", ",").split(",") if part.strip()]


def product_category_matches(product, normalized_category):
    target = normalized_category.lower()
    haystack = " ".join(
        filter(None, [product.category, product.sub_category, product.routine_step, product.time_of_use])
    ).lower()
    keyword_map = {
        "face": ["face", "cleanser", "serum", "moisturizer", "sunscreen", "toner"],
        "body": ["body", "lotion", "cream", "wash", "butter"],
        "hair": ["hair", "scalp", "shampoo", "conditioner", "oil", "mask"],
        "lips": ["lip", "balm", "lipcare"],
    }
    if target not in keyword_map:
        return target in haystack
    return any(keyword in haystack for keyword in keyword_map[target])


def skin_type_compatible(product_skin_text, user_skin_type):
    product_skins = [skin.lower() for skin in split_csv_text(product_skin_text)]
    user_skin = user_skin_type.lower()
    if not product_skins:
        return False, False
    if "all" in product_skins:
        return True, False
    return user_skin in product_skins, user_skin in product_skins


def product_matches_concern(product, concern_tokens):
    product_concerns = [concern.lower() for concern in split_csv_text(product.concerns)]
    matches = []
    for concern in concern_tokens:
        concern_lower = concern.lower()
        if concern_lower in product_concerns:
            matches.append(concern)
    return matches


def infer_effect_match(product, concern_tokens):
    text = " ".join(
        filter(None, [product.concerns, product.ingredients, product.sub_category, product.routine_step, product.name])
    ).lower()
    effect_keywords = {
        "acne": ["salicylic", "niacinamide", "acne", "oil", "clarifying"],
        "dryness": ["hyaluronic", "ceramide", "glycerin", "hydrating", "barrier"],
        "aging": ["retinol", "peptide", "vitamin c", "firming", "aging"],
        "dullness": ["vitamin c", "bright", "glow", "radiance"],
        "pigmentation": ["tranexamic", "alpha arbutin", "vitamin c", "pigment", "spot"],
        "sensitive": ["soothing", "calming", "centella", "ceramide", "oat"],
    }
    matched = []
    for concern in concern_tokens:
        keywords = effect_keywords.get(concern.lower(), [concern.lower()])
        if any(keyword in text for keyword in keywords):
            matched.append(concern)
    return matched


def is_beginner_friendly(product):
    flags = " ".join(filter(None, [product.beginner_friendly, product.experience_level])).lower()
    return "yes" in flags or "beginner" in flags or not flags.strip()


def product_is_harsh(product):
    text = " ".join(filter(None, [product.ingredients, product.name, product.sub_category])).lower()
    harsh_keywords = ["retinol", "glycolic", "aha", "bha", "peel", "exfoliating", "strong acid"]
    return any(keyword in text for keyword in harsh_keywords)


def build_user_profile(user_data):
    # Combine conversational concern data into additional_info
    additional_parts = []
    if user_data.get("symptoms"):
        additional_parts.append(f"Symptoms: {user_data.get('symptoms')}")
    if user_data.get("issue_history"):
        additional_parts.append(f"History: {user_data.get('issue_history')}")
    if user_data.get("current_products"):
        additional_parts.append(f"Current Products: {user_data.get('current_products')}")
    if user_data.get("triggers"):
        additional_parts.append(f"Triggers: {user_data.get('triggers')}")

    return {
        "flow": normalize_flow(user_data.get("intent")),
        "category": normalize_category(user_data),
        "skin_type": normalize_skin_type(user_data),
        "concern": normalize_concern_tokens(user_data),
        "age_group": normalize_age_group(user_data),
        "experience": normalize_experience(user_data),
        "routine_timing": user_data.get("routine") or "Complete",
        "budget": user_data.get("budget"),
        "specific_area": user_data.get("specific_area") or "",
        "additional_info": " | ".join(additional_parts) if additional_parts else "",
        "requested_count": user_data.get("product_count") or "",
        "kit_type": user_data.get("kit_type") or "",
    }


def score_and_filter_products(all_products, user_profile):
    category = user_profile["category"]
    skin_type = user_profile["skin_type"]
    concerns = user_profile["concern"]
    experience = user_profile["experience"]

    base_candidates = []
    relaxed_candidates = []

    for product in all_products:
        if not product_category_matches(product, category):
            continue

        compatible, exact_skin = skin_type_compatible(product.skin_type, skin_type)
        if not compatible:
            continue

        concern_matches = product_matches_concern(product, concerns)
        effect_matches = infer_effect_match(product, concerns)

        score = 0
        matched_attributes = []

        if concern_matches:
            score += 5 * len(concern_matches)
            matched_attributes.extend([f"concern:{match}" for match in concern_matches])

        if exact_skin:
            score += 3
            matched_attributes.append(f"skin_type:{skin_type}")
        else:
            score += 2
            matched_attributes.append("skin_type:All")

        if effect_matches:
            score += 2 * len(effect_matches)
            matched_attributes.extend([f"effect:{match}" for match in effect_matches])

        beginner_safe = is_beginner_friendly(product)
        if experience == "Beginner" and beginner_safe:
            score += 1
            matched_attributes.append("beginner_friendly")
        elif experience == "Beginner" and not beginner_safe:
            score -= 2
            matched_attributes.append("complex_for_beginner")

        if len((product.name or "").split()) <= 4:
            score += 1
            matched_attributes.append("simple_profile")

        if skin_type.lower() == "sensitive" and product_is_harsh(product):
            score -= 3
            matched_attributes.append("harsh_for_sensitive")

        candidate = {
            "product_id": product.product_id,
            "product_name": product.name,
            "category": product.category or "",
            "sub_category": product.sub_category or "",
            "skin_type": product.skin_type or "",
            "concerns": product.concerns or "",
            "ingredients": product.ingredients or "",
            "routine_step": product.routine_step or "",
            "time_of_use": product.time_of_use or "",
            "age_group": product.age_group or "",
            "experience_level": product.experience_level or "",
            "beginner_friendly": product.beginner_friendly or "",
            "price": product.price or "",
            "image": product.image or "",
            "app_score": score,
            "matched_attributes": matched_attributes,
        }

        relaxed_candidates.append(candidate)
        if concern_matches or not concerns:
            base_candidates.append(candidate)

    ranked = sorted(base_candidates, key=lambda item: item["app_score"], reverse=True)
    if not ranked:
        ranked = sorted(relaxed_candidates, key=lambda item: item["app_score"], reverse=True)

    return ranked


def choose_recommendation_count(user_profile):
    flow = user_profile["flow"]
    if flow == "Build My Routine":
        return 6
    if flow == "Help Me Fix a Concern":
        return 3
    requested_count = user_profile.get("requested_count")
    try:
        return max(3, min(6, int(requested_count)))
    except (TypeError, ValueError):
        return 4


def _build_natural_reason(item, user_profile):
    """Build a natural-language reason for why a product was selected."""
    attrs = item.get("matched_attributes", [])
    skin = user_profile.get("skin_type", "your").lower()
    concerns = user_profile.get("concern", [])
    experience = user_profile.get("experience", "Beginner").lower()

    parts = []
    concern_matches = [a.split(":")[1] for a in attrs if a.startswith("concern:")]
    effect_matches = [a.split(":")[1] for a in attrs if a.startswith("effect:")]

    if concern_matches:
        parts.append(f"directly targets your {' and '.join(concern_matches).lower()} concerns")
    if any(a.startswith("skin_type:") for a in attrs):
        parts.append(f"suited for {skin} skin")
    if "beginner_friendly" in attrs:
        parts.append("easy to work into any routine")
    if effect_matches and not concern_matches:
        parts.append(f"helps with {' and '.join(effect_matches).lower()}")
    if "harsh_for_sensitive" in attrs:
        parts.append("use with caution on sensitive areas")

    if not parts:
        parts.append("a strong match for your profile")

    return parts[0][0].upper() + parts[0][1:] + (", and " + ", ".join(parts[1:]) if len(parts) > 1 else "") + "."


def _build_natural_summary(user_profile):
    """Build a warm, conversational summary from the user profile."""
    skin = user_profile.get("skin_type", "balanced").lower()
    experience = user_profile.get("experience", "beginner").lower()
    category = user_profile.get("category", "skincare").lower()
    concerns = user_profile.get("concern", [])
    age = user_profile.get("age_group", "")
    flow = user_profile.get("flow", "")
    timing = user_profile.get("routine_timing", "Complete")

    concern_text = ", ".join([c.lower() for c in concerns[:3]]) if concerns else "overall skin health"
    age_text = f" in the {age} age range" if age else ""

    # Opening line — reference skin + concern
    opener = f"Since you have {skin} skin{age_text} and you're focusing on {concern_text}, "

    # What we did
    if flow == "Build My Routine":
        timing_label = {"Morning": "morning", "Evening": "evening"}.get(timing, "complete day-and-night")
        mid = f"I've put together a {timing_label} {category.lower()} routine that's "
    elif flow == "Create My Custom Kit":
        mid = f"I've curated a custom {category.lower()} kit that's "
    else:
        mid = f"I've picked {category.lower()} products that are "

    # Experience callout
    if experience == "beginner":
        tail = "simple and beginner-friendly — nothing overwhelming, just the essentials to get started."
    elif experience == "intermediate":
        tail = "a solid step up from the basics, with targeted actives that'll make a real difference."
    elif experience in ["advanced", "expert"]:
        tail = "built for someone who knows their way around actives — layered for maximum results."
    else:
        tail = "tailored to work well for your specific needs."

    return opener + mid + tail


def _build_local_analysis(user_profile):
    """Build a local analysis of the user's skin situation."""
    skin = user_profile.get("skin_type", "normal").lower()
    concerns = user_profile.get("concern", [])
    age = user_profile.get("age_group", "")
    category = user_profile.get("category", "face").lower()
    additional = user_profile.get("additional_info", "")
    specific_area = user_profile.get("specific_area", "").lower()

    # Handle Kit Analysis
    kit_type = user_profile.get("kit_type", "")
    if kit_type:
        kit_map = {
            "Travel Set": f"Travel is amazing, but it can really throw your skin for a loop! Airplane cabins are notoriously dry, and switching between different climates or water types can leave your {skin} skin feeling stressed. I’ve put together this kit to make sure your skin stays resilient, hydrated, and ready for adventure.",
            "Bridal Glow": f"The lead-up to your big day is so special, and your skin should reflect that! For your {skin} skin, we want to focus on a gentle, consistent glow. My goal here is to boost your natural radiance and keep things calm, so you feel confident and beautiful in every photo.",
            "Grooming Kit": f"A great grooming routine doesn't have to be complicated to be effective. For your {skin} skin, I'm focusing on high-impact products that handle everything from post-shave irritation to daily pollutants, keeping you looking sharp and refreshed with minimal effort.",
            "Daily Essentials": f"Think of these as your skin's daily 'must-haves.' For your {skin} skin, we're building a reliable foundation that handles the basics perfectly. It’s all about consistency—cleansing, treating, and protecting so your skin stays healthy and balanced every single day."
        }
        if kit_type in kit_map:
            return kit_map[kit_type]

    concern_text = concerns[0].lower() if concerns else "general skin health"

    # Build area-specific prefix when available (concern flow)
    area_prefix = ""
    if specific_area and specific_area not in ["", "entire face"]:
        area_prefix = f"Looking at your {specific_area}, "

    symptom_suffix = ""
    if additional:
        symptom_suffix = f" I noticed you mentioned feeling \"{additional}\"—that's a really helpful clue for us to target the right treatment."

    # Concern-specific root causes
    cause_map = {
        "acne": f"I know breakouts can be a total pain, but here's what's usually happening: {area_prefix}pores on {skin} skin can get clogged when oil and dead skin cells hang around a bit too long. {symptom_suffix} My plan is to clear things out gently so your skin can heal without feeling stripped.",
        "dryness": f"If your skin is feeling tight or parched, it's a sign your moisture barrier is asking for a little extra love. {area_prefix}On {skin} skin, this often happens when environmental factors or harsh products strip away your natural oils. {symptom_suffix} We're going to layer in some serious hydration to get that bounce back.",
        "dry": f"That tight, flaky feeling usually means your skin barrier is struggling to hold onto its natural moisture. {area_prefix}When {skin} skin is exposed to the elements or over-cleansed, it loses the oils it needs to stay soft. {symptom_suffix} Let's focus on sealing that hydration back in.",
        "aging": f"It's completely natural for our skin to change over time as collagen production slows down. {area_prefix}Starting a targeted routine now is a smart way to keep your {skin} skin firm and resilient. {symptom_suffix} We'll focus on ingredients that support renewal and protect against the elements.",
        "dullness": f"If you're missing that natural glow, it's usually because dead skin cells are building up on the surface, making things look a bit lackluster. {area_prefix}For {skin} skin, factors like stress or lack of sleep can show up as dullness. {symptom_suffix} We're going to brighten things up and reveal fresh, radiant skin.",
        "pigmentation": f"Uneven spots or marks are just your skin over-reacting to things like sun exposure or past breakouts. {area_prefix}For {skin} skin, consistency is the key to fading those marks and keeping your tone even. {symptom_suffix} We'll use gentle brighteners to help your skin find its balance.",
        "sensitive": f"Dealing with reactive skin can be a bit of a balancing act! {area_prefix}Sensitivity on {skin} skin means your barrier is a little extra vulnerable right now. {symptom_suffix} My goal is to soothe any redness and strengthen your skin so it feels calm and comfortable again.",
        "oily": f"Having oily skin is actually a sign of very productive sebaceous glands, which can be a blessing as we age! {area_prefix}The trick for your {skin} skin is to balance that oil without stripping it away, which actually triggers the skin to produce even more. {symptom_suffix}",
        "red": f"Visible redness is usually your skin's way of telling us it's a bit irritated or inflamed. {area_prefix}Whether it's from the weather or a new product, your {skin} skin needs some soothing care. {symptom_suffix} We'll focus on calming ingredients to bring down that heat.",
        "flaky": f"Flakiness is essentially your skin barrier reaching out for help. {area_prefix}On {skin} skin, it means those surface cells aren't shedding properly because they're lacking moisture. {symptom_suffix} We're going to gently smooth things over and deeply hydrate.",
    }

    analysis = cause_map.get(concern_text, "")

    # If no direct match, try to match from symptoms text
    if not analysis and additional:
        additional_lower = additional.lower()
        for key in cause_map:
            if key in additional_lower:
                analysis = cause_map[key]
                break

    if not analysis:
        analysis = f"{area_prefix}Your {skin} skin in the {specific_area or category} area needs targeted attention. The concerns you've described are common and very treatable with the right product combination.{symptom_suffix}"

    return analysis.strip()


def _build_local_solution(user_profile):
    """Build a local solution strategy description."""
    skin = user_profile.get("skin_type", "normal").lower()
    concerns = user_profile.get("concern", [])
    experience = user_profile.get("experience", "beginner").lower()
    flow = user_profile.get("flow", "")
    additional = user_profile.get("additional_info", "").lower()

    # Handle Kit Solution
    kit_type = user_profile.get("kit_type", "")
    if kit_type:
        kit_sol_map = {
            "Travel Set": "My strategy for your trip is all about 'Hydration on the Go.' We’re using TSA-friendly sizes that prioritize barrier repair and deep moisture, so you can combat that dry airplane air and arrive looking refreshed.",
            "Bridal Glow": "The approach here is 'Gentle Radiance.' We’re avoiding anything too aggressive and instead focusing on soothing hydrators and brightening antioxidants that work with your {skin} skin to reveal a healthy, natural glow.",
            "Grooming Kit": "We’re going for a 'Clean & Balanced' approach. I’ve picked multi-tasking heroes that work quickly to soothe skin, control any unwanted shine, and keep your {skin} skin feeling hydrated without any heavy or greasy residue.",
            "Daily Essentials": "Our strategy is 'Foundation First.' I’ve selected a core trio that targets your specific needs while keeping things simple enough to stick with every day. It’s the perfect baseline for healthy, happy skin."
        }
        if kit_type in kit_sol_map:
            return kit_sol_map[kit_type]

    concern_text = concerns[0].lower() if concerns else "general care"

    solution_map = {
        "acne": "The best way forward is to be 'Gentle but Effective.' I've picked a cleanser with salicylic acid to clear those pores without making your skin feel tight, paired with a light moisturizer to keep things balanced.",
        "dryness": "Our goal is a 'Moisture Reset.' We're going to layer in hydrating ingredients that pull water into your skin, then seal it all in with a rich cream to stop it from escaping.",
        "dry": "We're going to focus on 'Repair & Restore.' A creamy cleanser and a ceramide-rich moisturizer will help rebuild your barrier and get rid of that tight feeling for good.",
        "aging": "The focus is on 'Protect & Renew.' We'll use gentle actives in the evening to help with cell turnover, and plenty of antioxidants and SPF in the morning to keep your {skin} skin looking its best.",
        "dullness": "The plan is a 'Radiance Boost.' We'll gently sweep away the old surface cells and use brightening serums to help your natural glow shine through.",
        "pigmentation": "We're taking a 'Dual Action' approach: treating existing spots with brighteners like Vitamin C, while preventing new ones with consistent daily protection.",
        "sensitive": "The priority is 'Calm & Comfort.' I've selected fragrance-free, soothing products that focus on strengthening your barrier while calming any redness or heat.",
        "oily": "The goal is 'Smart Balance.' We're using lightweight, gel-based products that hydrate your skin perfectly without adding any extra weight or shine.",
        "red": "We're going for 'Instant Calm.' Think of this as a soothing hug for your skin—lots of centella and niacinamide to bring down redness and make your skin feel peaceful again.",
        "flaky": "The solution is 'Smooth & Seal.' A very mild exfoliant to clear the flakes, followed by a deeply nourishing moisturizer to make sure they don't come back.",
    }

    solution = solution_map.get(concern_text, "")

    # Try to match from symptoms if no direct concern match
    if not solution and additional:
        for key in solution_map:
            if key in additional:
                solution = solution_map[key]
                break

    if not solution:
        solution = f"I've selected products that complement your {skin} skin type and address your specific needs without overcomplicating your routine."

    if experience == "beginner":
        solution += " Since you're a beginner, I've kept this simple — no overwhelming multi-step routine, just the essentials."
    elif experience in ["advanced", "expert"]:
        solution += " Since you're experienced, I've included some potent actives that can be layered for maximum impact."

    return solution


def _build_local_description(item):
    """Build a product description from its attributes."""
    name = item.get("product_name", "Product")
    sub_cat = item.get("sub_category", "").lower()
    ingredients = item.get("ingredients", "")
    concerns = item.get("concerns", "")
    intensity = item.get("beginner_friendly", "").lower()

    # Build description from available data
    ing_list = [i.strip() for i in ingredients.split(",") if i.strip()][:3]
    ing_text = f" with {', '.join(ing_list)}" if ing_list else ""

    type_text = sub_cat if sub_cat else "skincare product"
    return f"A {type_text}{ing_text} designed to address {concerns.lower() if concerns else 'your skin concerns'}."


def build_local_structured_recommendation(scored_products, user_profile):
    limit = choose_recommendation_count(user_profile)
    selected = scored_products[:limit]
    recommendations = []

    for item in selected:
        recommendations.append({
            "product_name": item["product_name"],
            "score": item["app_score"],
            "description": _build_local_description(item),
            "reason": _build_natural_reason(item, user_profile),
            "matched_attributes": item["matched_attributes"][:6],
        })

    morning = []
    evening = []
    if user_profile["flow"] == "Build My Routine":
        for item in selected:
            step = (item["routine_step"] or item["sub_category"]).lower()
            time_of_use = (item["time_of_use"] or "").lower()
            name = item["product_name"]
            if "morning" in time_of_use or "am" in time_of_use or "sunscreen" in step:
                if name not in morning:
                    morning.append(name)
            if "evening" in time_of_use or "pm" in time_of_use or any(token in step for token in ["serum", "treatment", "retinol", "moisturizer", "cleanser"]):
                if name not in evening:
                    evening.append(name)

        if not morning:
            morning = [item["product_name"] for item in selected[: min(4, len(selected))]]
        if not evening:
            evening = [item["product_name"] for item in selected[: min(4, len(selected))]]

        step_cap = 4 if user_profile["experience"] == "Beginner" else 6
        morning = morning[:step_cap]
        evening = evening[:step_cap]

        timing = user_profile.get("routine_timing")
        if timing == "Morning":
            evening = []
        elif timing == "Evening":
            morning = []

    # Build a warm, specific title
    concerns = user_profile.get("concern", [])
    skin = user_profile.get("skin_type", "Your")
    category = user_profile.get("category", "Skincare")
    flow = user_profile.get("flow", "")

    concern_label = f" for {concerns[0]}" if concerns else ""
    if flow == "Build My Routine":
        timing = user_profile.get("routine_timing", "Complete")
        timing_label = {"Morning": "Morning", "Evening": "Evening"}.get(timing, "Daily")
        title = f"Your {timing_label} {category} Routine{concern_label}"
    elif flow == "Create My Custom Kit":
        title = f"Your Custom {category} Kit{concern_label}"
    else:
        title = f"Your {category} Picks{concern_label}"

    return {
        "title": title,
        "analysis": _build_local_analysis(user_profile),
        "solution": _build_local_solution(user_profile),
        "recommendations": recommendations,
        "routine": {"morning": morning, "evening": evening},
        "notes": f"Start with just the cleanser and moisturizer for the first week, then layer in the other products one at a time. Always patch-test on a small area first — your {skin.lower()} skin will thank you!",
    }


def format_structured_message(result, flow=None):
    # Add a warm, conversational opening
    intro_map = {
        "Build My Routine": "I've carefully crafted this routine to work with your skin's natural rhythm. Here’s what I’m thinking!",
        "Help Me Fix a Concern": "I've analyzed your concern, and I have a clear plan to help your skin feel its best again.",
        "Create My Custom Kit": "I've put together a special kit just for you. It’s simple, effective, and exactly what you asked for!"
    }
    intro = intro_map.get(flow, "I've analyzed your skin profile—here is my expert advice for you.")

    lines = [f"## {result.get('title') or 'Your Personalized Recommendations'}", "", intro]

    # Section 1: Analysis
    analysis = result.get("analysis")
    if analysis:
        lines.append("")
        if flow == "Help Me Fix a Concern":
            header = "**🧐 Why this is happening**"
        elif flow == "Create My Custom Kit":
            header = "**🔍 Kit Analysis**"
        else:
            header = "**🔍 Skin Analysis**"
        lines.append(header)
        lines.append(analysis)

    # Section 2: Solution
    solution = result.get("solution")
    if solution:
        lines.append("")
        if flow == "Help Me Fix a Concern":
            header = "**💡 The Solution**"
        elif flow == "Create My Custom Kit":
            header = "**💡 Kit Strategy**"
        else:
            header = "**💡 Our Approach**"
        lines.append(header)
        lines.append(solution)

    # Section 3: Product Recommendation
    recommendations = result.get("recommendations") or []
    if recommendations:
        lines.append("")
        if flow == "Help Me Fix a Concern":
            header = "**🛍️ Product Recommendation**"
        elif flow == "Create My Custom Kit":
            header = "**📦 Your Recommended Kit**"
        else:
            header = "**🧴 Recommended Products**"
        lines.append(header)
        for idx, rec in enumerate(recommendations, start=1):
            name = rec.get('product_name', 'Product')
            description = rec.get("description", "").rstrip(".")
            reason = rec.get("reason", "A great fit for your skin.").rstrip(".")

            lines.append(f"")
            lines.append(f"**{idx}. {name}**")
            if description:
                lines.append(f"{description}.")
            lines.append(f"_Why this one? {reason}._")

    # Section 4: Routine steps (Skip for Custom Kit)
    if flow != "Create My Custom Kit":
        routine = result.get("routine") or {}
        morning = routine.get("morning") or []
        evening = routine.get("evening") or []
        if morning or evening:
            if morning:
                lines.append("")
                lines.append("**☀️ Morning Routine**")
                for idx, product_name in enumerate(morning, start=1):
                    lines.append(f"- Step {idx}: {product_name}")

            if evening:
                lines.append("")
                lines.append("**🌙 Evening Routine**")
                for idx, product_name in enumerate(evening, start=1):
                    lines.append(f"- Step {idx}: {product_name}")

    # Section 5: Pro tip
    notes = result.get("notes")
    if notes:
        lines.append("")
        lines.append(f"**✨ Pro Tip:** {notes}")

    return "\n".join(lines)


def _fuzzy_find_product(product_name, product_map, all_products):
    """Find a product by name using progressively looser matching."""
    name = product_name.strip().lower()
    if not name:
        return None

    # 1. Exact match
    if name in product_map:
        return product_map[name]

    # 2. Normalized match (collapse extra whitespace)
    normalized = " ".join(name.split())
    if normalized in product_map:
        return product_map[normalized]

    # 3. Substring match — check if AI name is contained in a DB name or vice versa
    for db_name, product in product_map.items():
        if name in db_name or db_name in name:
            return product

    # 4. Word-overlap match — find the product with the most words in common
    name_words = set(name.split())
    best_match = None
    best_overlap = 0
    for db_name, product in product_map.items():
        db_words = set(db_name.split())
        overlap = len(name_words & db_words)
        if overlap > best_overlap and overlap >= 2:
            best_overlap = overlap
            best_match = product

    return best_match


def map_recommendations_to_products(recommendations, all_products, scored_shortlist=None):
    """Map AI recommendations to product cards. Uses fuzzy matching and
    falls back to the scored shortlist to guarantee every recommendation gets a card."""
    product_map = {product.name.lower().strip(): product for product in all_products}
    product_list = []
    seen = set()

    for recommendation in recommendations:
        product_name = (recommendation.get("product_name") or "").strip().lower()
        if not product_name or product_name in seen:
            continue
        seen.add(product_name)

        product = _fuzzy_find_product(product_name, product_map, all_products)
        if not product:
            print(f"[WARN] Could not match product: '{product_name}'")
            continue

        brand = product.name.split(" ")[0] if " " in product.name else "Skincare"
        product_list.append({
            "name": product.name,
            "brand": brand,
            "price": product.price,
            "image": product.image
        })

    # If we still have fewer cards than recommendations, fill from the scored shortlist
    if scored_shortlist and len(product_list) < len(recommendations):
        existing_names = {p["name"].lower() for p in product_list}
        for item in scored_shortlist:
            if len(product_list) >= len(recommendations):
                break
            item_name = item.get("product_name", "").lower()
            if item_name in existing_names:
                continue
            product = product_map.get(item_name)
            if not product:
                continue
            existing_names.add(item_name)
            brand = product.name.split(" ")[0] if " " in product.name else "Skincare"
            product_list.append({
                "name": product.name,
                "brand": brand,
                "price": product.price,
                "image": product.image
            })

    return product_list


def pick_products_for_fallback(all_products, user_data, limit=4):
    user_profile = build_user_profile(user_data)
    scored_products = score_and_filter_products(all_products, user_profile)
    chosen_names = {item["product_name"] for item in scored_products[:limit]}
    chosen = [product for product in all_products if product.name in chosen_names]
    return chosen or all_products[: min(limit, len(all_products))]


def build_local_routine(all_products, user_data):
    area = user_data.get("focus") or user_data.get("area") or "Skincare"
    skin_type = user_data.get("skin") or user_data.get("skin_type") or "balanced"
    chosen_products = pick_products_for_fallback(all_products, user_data)

    morning_products = chosen_products[:2]
    night_products = chosen_products[2:4] if len(chosen_products) > 2 else chosen_products[:1]

    lines = [
        f"## Custom Routine for your {area}",
        f"**Overview**: Here is a practical routine for {skin_type.lower()} skin based on your answers and the products currently available in your catalog.",
        "",
        "### Morning Routine:"
    ]

    if morning_products:
        for idx, product in enumerate(morning_products, start=1):
            lines.append(f"- **Step {idx}: {product.name}** - Use a small amount and apply consistently for best results.")
    else:
        lines.append("- **Step 1: Gentle cleanse and hydrate** - Keep the routine simple while the AI service is unavailable.")

    lines.extend(["", "### Night Routine:"])
    if night_products:
        for idx, product in enumerate(night_products, start=1):
            lines.append(f"- **Step {idx}: {product.name}** - Apply in the evening and monitor how your skin responds.")
    else:
        lines.append("- **Step 1: Cleanse and nourish** - Focus on recovery and barrier support overnight.")

    lines.extend([
        "",
        "**Pro Tip**: Patch-test new products first and introduce only one new product at a time."
    ])

    return "\n".join(lines), chosen_products


def generate_routine(user_data, db):
    all_products = db.query(Product).all()
    user_profile = build_user_profile(user_data)
    scored_products = score_and_filter_products(all_products, user_profile)
    shortlisted_products = scored_products[: max(8, choose_recommendation_count(user_profile) + 2)]

    try:
        top_matches = retrieve_top_k(user_data, k=1)
        best_routine_guide = top_matches[0]['record']['recommended_routine']
    except Exception as e:
        print(f"RAG Error: {e}")
        best_routine_guide = "Standard daily routine"

    request_payload = {
        "user_profile": user_profile,
        "routine_guide": best_routine_guide,
        "selection_rule": {
            "target_recommendation_count": choose_recommendation_count(user_profile),
            "use_shortlist_as_primary_truth": True,
        },
        "product_dataset": shortlisted_products,
    }

    ai_text = ask_llm_safe(json.dumps(request_payload, ensure_ascii=True), system_prompt=RECOMMENDATION_SYSTEM_PROMPT)

    structured_result = None
    if ai_text:
        try:
            structured_result = json.loads(ai_text)
        except json.JSONDecodeError as e:
            print(f"JSON parse error: {e}")

    if not structured_result:
        structured_result = build_local_structured_recommendation(shortlisted_products, user_profile)

    recommendations = structured_result.get("recommendations") or []
    
    # Enforce strict count for Custom Kit flow
    target_count = choose_recommendation_count(user_profile)
    if user_profile["flow"] == "Create My Custom Kit":
        if len(recommendations) > target_count:
            recommendations = recommendations[:target_count]

    # Pass scored shortlist so missing products can be filled from it
    product_list = map_recommendations_to_products(recommendations, all_products, scored_shortlist=shortlisted_products)

    if user_profile["flow"] == "Create My Custom Kit":
        if len(product_list) > target_count:
            product_list = product_list[:target_count]
    final_message = format_structured_message(structured_result, flow=user_profile.get("flow"))

    # Final safety net — if still no product cards, pull from scored shortlist directly
    if len(product_list) < len(recommendations) and shortlisted_products:
        existing_names = {p["name"].lower() for p in product_list}
        product_map = {product.name.lower().strip(): product for product in all_products}
        for item in shortlisted_products:
            if len(product_list) >= len(recommendations):
                break
            item_name = item.get("product_name", "").lower()
            if item_name in existing_names:
                continue
            product = product_map.get(item_name)
            if not product:
                continue
            existing_names.add(item_name)
            brand = product.name.split(" ")[0] if " " in product.name else "Skincare"
            product_list.append({
                "name": product.name,
                "brand": brand,
                "price": product.price,
                "image": product.image
            })

    if not product_list and all_products:
        fallback_products = pick_products_for_fallback(all_products, user_data, limit=len(recommendations) or 4)
        for p in fallback_products:
            product_list.append({
                "name": p.name,
                "brand": p.name.split(' ')[0],
                "price": p.price,
                "image": p.image
            })

    return {
        "type": "input",
        "message": final_message,
        "products": product_list,
        "placeholder": "Ask a question about the routine...",
        "next_step": 999,
        "data_key": "follow_up_chat"
    }
def handle_follow_up_chat(step, user_data, db):
    user_query = user_data.get("follow_up_chat", "Hello")

    intent = user_data.get("intent", "Skincare")
    skin_type = user_data.get("skin") or user_data.get("skin_type") or "Normal"
    focus = user_data.get("focus") or user_data.get("area") or "Face"
    experience = user_data.get("experience", "Beginner")
    age = user_data.get("age", "18-24")
    routine_timing = user_data.get("routine", "Complete")

    routine_info = ""
    if user_data.get("routine"):
        morning = user_data.get("morning_routine", [])
        evening = user_data.get("evening_routine", [])
        if morning:
            routine_info += f"\n**Morning Routine:**\n- " + "\n- ".join(morning)
        if evening:
            routine_info += f"\n**Evening Routine:**\n- " + "\n- ".join(evening)

    products_info = ""
    if user_data.get("recommended_products"):
        prods = user_data.get("recommended_products", [])
        products_info = "\n**Your Recommended Products:**\n"
        for p in prods[:6]:
            products_info += f"- {p.get('name', 'Unknown')}\n"

    prompt = f"""
You are an expert Skincare Consultant with 15+ years of experience. Your tone is warm, professional, and scientific but accessible.

--- USER PROFILE ---
- Intent: {intent}
- Skin Type: {skin_type}
- Focus Area: {focus}
- Experience Level: {experience}
- Age Range: {age}
- Routine Timing: {routine_timing}
{routine_info}
{products_info}

--- USER'S QUESTION ---
"{user_query}"

--- RESPONSE RULES ---
1. Answer **directly and specifically** - never deflect or defer unnecessarily
2. If they ask about a product, explain its purpose, when to use it, and how much to apply
3. If they ask about routine order, specify the exact sequence with timing (AM/PM)
4. If they mention a skin concern (redness, breakouts, dryness), give actionable advice
5. Keep responses under 120 words unless they ask for detail
6. Use **bold headers** for sections, **bold key terms** within text
7. Never start with "Based on your profile" - just answer the question
8. If unsure about a specific product, suggest they patch test first

Provide your answer now:
"""

    ai_text = ask_llm_safe(prompt)
    if not ai_text:
        ai_text = (
            "I'm having trouble connecting to the AI service right now. "
            "You can still ask me about product order, timing, layering, or how to introduce new actives - "
            "or click 'Start Over' to begin a new consultation."
        )

    return {
        "type": "input",
        "message": ai_text,
        "placeholder": "Ask about products, routine, or skin concerns...",
        "next_step": 999,
        "data_key": "follow_up_chat"
    }


# ---------------- MAIN ROUTER ---------------- #

@app.post("/api/chat")
async def chat_endpoint(req: ChatRequest, db: Session = Depends(get_db)):
    try:
        step = req.step
        user_data = req.data

        if step == 0:
            return {
                "message": "Hi! What can I help you with?",
                "options": [
                    "Build my Routine",
                    "Help Me Fix a Concern",
                    "Create My Custom Kit"
                ],
                "next_step": 1,
                "data_key": "intent"
            }

        intent = user_data.get("intent")

        if step >= 999:
            return handle_follow_up_chat(step, user_data, db)

        if intent == "Build my Routine":
            return handle_routine_flow(step, user_data, db)

        elif intent == "Help Me Fix a Concern":
            return handle_concern_flow(step, user_data, db)

        elif intent == "Create My Custom Kit":
            return handle_kit_flow(step, user_data, db)

        return {"message": "Invalid flow", "options": []}
    except Exception as e:
        print(f"Chat endpoint error: {e}")
        raise HTTPException(status_code=500, detail="The chatbot hit an internal error while building your result.")


# ---------------- FRONTEND STATIC FILES ---------------- #
frontend_path = os.path.join(BASE_DIR, "..", "frontend")

@app.get("/")
async def serve_index():
    return FileResponse(os.path.join(frontend_path, "index.html"))

# Mount the rest of the frontend files (app.js, style.css, images, etc.)
app.mount("/", StaticFiles(directory=frontend_path), name="frontend")


if __name__ == "__main__":
    import os
    port = int(os.environ.get("PORT", 8001))
    uvicorn.run(app, host="0.0.0.0", port=port)
